[package]
name = "ostrel_db"
description = "Abstract database interface between generated server code and database drivers."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ostrel_core.workspace = true

[lints]
workspace = true
