[package]
name = "ostrel_db_memory"
description = "In memory database driver of the Ostrel programming language, also the template for new drivers."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ostrel_db.workspace = true

[lints]
workspace = true
